version: "3"
services:
  postgres:
    build: .
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # This will ensure our data persiststo our local project when we stop/start docker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - 21717:21717
